name: opera-demo
channels:
  - conda-forge
dependencies:
 - jupyterlab
 - matplotlib
 - rasterio
 - pandas
 - pystac
 - gdal
 - contextily
 - folium
 - pystac-client
 - shapely
 - ipyleaflet
 - geopandas
 - pdal
 - pyproj